# FIELDNAMES
KILLED_BY = 'killed_by'
KILLED_NAME = 'killer_name'
KILLER_PLACEMENT = 'killer_placement'
KILLER_X = 'killer_x_metres'
KILLER_Y = 'killer_y_metres'
MAPNAME = 'map'
MATCH_ID = 'match_id'
TIME_SECONDS = 'time'
VICTIM_NAME = 'victim_name'
VICTIM_PLACEMENT = 'victim_placement'
VICTIM_X = 'victim_x_metres'
VICTIM_Y = 'victim_y_metres'
